@ComposerApi_HostAddress = http://localhost:5250

### Should find
###

GET {{ComposerApi_HostAddress}}/product/123

### Not found
###

GET {{ComposerApi_HostAddress}}/product/456

### Results
###

GET {{ComposerApi_HostAddress}}/products?searchTerm=abc

### No results
###

GET {{ComposerApi_HostAddress}}/products?searchTerm=def

### Should find
###

GET {{ComposerApi_HostAddress}}/async-product/123

### Not found
###

GET {{ComposerApi_HostAddress}}/async-product/456

### Results
###

GET {{ComposerApi_HostAddress}}/async-products?searchTerm=abc

### No results
###

GET {{ComposerApi_HostAddress}}/async-products?searchTerm=def